language: python
python:
  - 3.8

install: # --ignore-pipfile --deploy
  - pipenv install --dev

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-0.7.0-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - pytest

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
# before_deploy: echo "Before Deployment - This deploy was PUSHED by By - amartinez via Local"
# deploy:
#   skip_cleanup: true
#   on:
#     branch: main
#   provider: script
#   script: pipenv run pytest
