language: python
python:
  - 3.8

install: # --ignore-pipfile --deploy
  - pipenv install --dev --ignore-pipfile --deploy

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $CC_TEST_REPORTER_ID

before_deploy: echo "Before Deployment - This deploy was PUSHED by By - amartinez via Local"
deploy:
  skip_cleanup: true
  on:
    branch: main
  provider: script
  script: pipenv run pytest
